import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { TrustedTypesScript } from "@/components/TrustedTypesScript";
import { LangProvider } from "@/lib/i18n";
import "./globals.css";

const SITE = "https://jokomerce.de";

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: {
    default: "Jokomerce — Marketplace & D2C Wachstum mit P&L-Verantwortung",
    template: "%s · Jokomerce",
  },
  description:
    "Joachim Heidel — Head of Marketplace & CMO auf Zeit. End-to-end Verantwortung für Marketplace & D2C Wachstum mit P&L-Ownership in DE und US.",
  applicationName: "Jokomerce",
  authors: [{ name: "Joachim Heidel", url: "https://www.linkedin.com/in/joachim-heidel-803b36134/" }],
  creator: "Joachim Heidel",
  publisher: "Jokomerce",
  keywords: [
    "Marketplace Consulting",
    "Head of Marketplace",
    "Interim CMO",
    "Amazon Growth",
    "D2C Shopify",
    "Multichannel",
    "Otto Kaufland Walmart",
    "P&L Ownership",
    "Joachim Heidel",
    "Jokomerce",
    "E-Commerce Beratung",
    "Köln Bonn",
  ],
  openGraph: {
    type: "website",
    locale: "de_DE",
    alternateLocale: ["en_US"],
    siteName: "Jokomerce",
    url: SITE,
    title: "Jokomerce — Marketplace & D2C Wachstum mit P&L-Verantwortung",
    description:
      "Joachim Heidel — Head of Marketplace & CMO auf Zeit. End-to-end P&L-Verantwortung für Marketplace & D2C in DE und US.",
    // opengraph-image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Jokomerce — Marketplace & D2C Wachstum mit P&L-Verantwortung",
    description:
      "Joachim Heidel — Head of Marketplace & CMO auf Zeit. End-to-end P&L-Verantwortung über Amazon, Otto, Shopify und mehr.",
  },
  alternates: {
    canonical: SITE,
    languages: { "de-DE": SITE, "en-US": `${SITE}?lang=en` },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  // icon + apple-icon auto-generated by app/icon.tsx and app/apple-icon.tsx
  category: "consulting",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FFFFFF" },
    { media: "(prefers-color-scheme: dark)", color: "#0A0A0A" },
  ],
  width: "device-width",
  initialScale: 1,
};

// JSON-LD: Person + ProfessionalService
const PERSON_LD = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Joachim Heidel",
  jobTitle: "Head of Marketplace & Interim CMO",
  url: SITE,
  image: `${SITE}/joachim/joachim-hero.jpg`,
  sameAs: ["https://www.linkedin.com/in/joachim-heidel-803b36134/"],
  worksFor: { "@type": "Organization", name: "Jokomerce", url: SITE },
  knowsAbout: [
    "Marketplace Growth",
    "Amazon Catalogue",
    "Multichannel E-Commerce",
    "Shopify D2C",
    "Profit & Loss Ownership",
    "ERP Operations",
    "AI Workflows",
  ],
  address: { "@type": "PostalAddress", addressLocality: "Köln", addressRegion: "NRW", addressCountry: "DE" },
};

const SERVICE_LD = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  name: "Jokomerce",
  description:
    "Marketplace & D2C operator-as-a-service. End-to-end P&L ownership across Amazon, Otto, Kaufland, Walmart, Shopify and more.",
  url: SITE,
  founder: { "@type": "Person", name: "Joachim Heidel" },
  areaServed: ["DE", "EU", "US"],
  serviceType: [
    "Head of Marketplace",
    "Interim CMO",
    "Amazon Growth",
    "Multichannel Expansion",
    "Shopify D2C Growth",
    "Operations & ERP",
    "Customer Support Setup",
    "AI Workflows",
  ],
  priceRange: "€€€",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Nonce is set by middleware.ts and forwarded via x-nonce request header.
  // Inline scripts that should pass the strict CSP must carry this nonce.
  const nonce = headers().get("x-nonce") ?? undefined;

  return (
    <html
      lang="de"
      data-accent="yellow"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <head>
        {/* Must run FIRST — installs a Trusted Types default policy before
            React or webpack touch any innerHTML / script.src sinks. */}
        <TrustedTypesScript nonce={nonce} />
      </head>
      <body>
        <script
          type="application/ld+json"
          nonce={nonce}
          dangerouslySetInnerHTML={{ __html: JSON.stringify(PERSON_LD) }}
        />
        <script
          type="application/ld+json"
          nonce={nonce}
          dangerouslySetInnerHTML={{ __html: JSON.stringify(SERVICE_LD) }}
        />
        <LangProvider>
          <Nav />
          {children}
          <Footer />
        </LangProvider>
      </body>
    </html>
  );
}
